import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { IdleTimer } from "@/components/domain/auth/idle-timer";
import { LogoutButton } from "@/components/domain/auth/logout-button";
import { auth } from "@/server/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {session ? (
          // Placeholder mínimo hasta el shell real (Sidebar/BottomNav) de
          // Sprint 2 — acá solo se garantiza que el logout sea alcanzable.
          <div className="flex justify-end p-4">
            <LogoutButton />
          </div>
        ) : null}
        {children}
        {session ? <IdleTimer /> : null}
      </body>
    </html>
  );
}
