import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { IdleTimer } from "@/components/domain/auth/idle-timer";
import { BottomNav } from "@/components/layout/bottom-nav";
import { Sidebar } from "@/components/layout/sidebar";
import { auth } from "@/server/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const rol = session?.user?.rol;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {rol ? (
          <div className="flex min-h-full flex-1">
            <Sidebar rol={rol} />
            {/* pb-16 en mobile: deja espacio para el BottomNav fijo (S2-10) */}
            <div className="flex flex-1 flex-col pb-16 md:pb-0">{children}</div>
          </div>
        ) : (
          children
        )}
        {rol ? <BottomNav rol={rol} /> : null}
        {rol ? <IdleTimer /> : null}
      </body>
    </html>
  );
}
